server:
  port: 8080

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
          gateway.route.RouteDefinitionRouteLocator: INFO
    root: INFO


spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: FILE-SERVICE
          uri: lb://FILE-SERVICE
          predicates:
            - Path=/api/v1/file/**
#          filters:
#            - CustomFilter
#            - name: CircuitBreaker
#              args:
#                name: FILE-SERVICE
#                fallbackUri: forward:/file-service-fallback
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/product/**
#          filters:
#            - CustomFilter
#            - name: CircuitBreaker
#              args:
#                name: PRODUCT-SERVICE
#                fallbackUri: forward:/product-service-fallback
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**
#          filters:
#            - CustomFilter
#            - name: CircuitBreaker
#              args:
#                name: USER-SERVICE
#                fallbackUri: forward:/user-service-fallback
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order/**
#          filters:
#            - CustomFilter
#            - name: CircuitBreaker
#              args:
#                name: ORDER-SERVICE
#                fallbackUri: forward:/order-service-fallback