server:
  port: 8082

spring:
  application:
    name: FILE-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/file_service_db
    username: postgres
    password: Sql123
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

file:
  upload-dir: file-service/src/main/resources/images
  url: ${FILE_UPLOAD_URL:http://localhost:8080/api/v1/file}